name: manual test
on:
  workflow_dispatch

jobs:
  do-some:
    runs-on: ubuntu-latest
    environment: develop
    env:
       NODE_VERSION: 22
    steps:
      - name: 1 read local
        run: echo "my local node is ${{ env.NODE_VERSION }}

      - name: 2 read env var
        run: echo "my local node is ${{ vars.NODE_VERSION }}

      - name: 3 read env var
        run: echo "my environment node is ${{ NODE_VERSION }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - run: node --version
