name: manual test
on:
  workflow_dispatch

jobs:
  do-some:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: ${{ vars.NODE_VERSION }}
    environment: develop
    steps:
      - name: Read a local variable
        run: echo "My NODE_VERSION value is ${{ vars.APP_ID }}"
    
      - name: Read a global variable $NODE_VERSION
        run: echo "My global NODE_VERSION value is {{ $NODE_VERSION }}"
