name: manual test
on:
  workflow_dispatch

jobs:
  do-some:
    runs-on: ubuntu-latest
    environment: develop
    env:
       NODE_VERSION: 22
    steps:
      - name: 1 read local
        run: echo "my local node is ${{ env.NODE_VERSION }}"

      - name: 2 read env var
        run: echo "my local node is ${{ vars.NODE_VERSION }}"

      - name: 3 read env var
        run: echo "my environment node is $NODE_VERSION"

      - name: 4 github env
        run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat ./package.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: 5 github env
      - run: |
          echo '${{ fromJson(env.PACKAGE_JSON).engines.node }}'

      - name: Read package.json node version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        id: package-node-version
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.package-node-version.outputs.current-version }}
      - run: node --version
